### ISSUE TITLE
USER STORY: Create, read, update and delete blog posts

### ISSUE THREAD

**Issue by MariaHochstoeger** [MariaHochstoeger/el-madre#1]
As a **Site Admin** I can **create, read, update and delete posts** so that **I can manage the blog content**.

**Acceptance Criteria**

- [x] When logged in as the site admin, I can create a blog post
- [x] When logged in as the site admin, I can read a blog post
- [x] When logged in as the site admin, I can update a blog post
- [x] When logged in as the site admin, I can delete a blog post

**Tasks**

- [x] Create an admin user
- [x] Create a blog post model
- [x] Test blog post creation functionality
