### ISSUE TITLE
USER STORY: View a post in full

### ISSUE THREAD

**Issue by MariaHochstoeger** [MariaHochstoeger/el-madre#10]
As a **site user** I can **view a post in full** so that **I can read its contents**.

**Acceptance Criteria**

- [x] Upon clicking on a post in the paginated view, the post opens on a single page
- [x] The full post can be read

**Tasks**

- [x] Design and implement a template for viewing a single post 
- [x] Test the functionality
