### ISSUE TITLE
USER STORY: Register an account

### ISSUE THREAD

**Issue by MariaHochstoeger** [MariaHochstoeger/el-madre#2]
As a **user** I can **register an account** so that **I can benefit from additional functionality such as commenting**.

**Acceptance Criteria**

- [x] Easy account setup with username and password
- [x] After setting up an account, the user can log in and out
- [x] One logged in, the user enjoys additional functionality such as being able to comment

**Tasks**

- [x] Implement account setup
- [x] Ensure safety of account
