### ISSUE TITLE
USER STORY: View a site of posts

### ISSUE THREAD

**Issue by MariaHochstoeger** [MariaHochstoeger/el-madre#3]
As a **site user** I can **view a paginated list of posts** so that **I have a good overview and can choose which post to view in detail**.

**Acceptance Criteria**

- [x] A list of 3 posts per paginated site are displayed in the main view
- [x] Upon visiting the main page, a list of 3 posts is displayed
- [x] Intuitive design which lets the user choose which post to read in full

**Tasks**

- [x] Design and implement a paginated view
- [x] Test moving from one paginated site to another
