### ISSUE TITLE
USER STORY: Comment on posts

### ISSUE THREAD

**Issue by MariaHochstoeger** [MariaHochstoeger/el-madre#4]
As a **logged in Site User** I can **comment on posts** so that **I can share my view on a given blog post**.

**Acceptance Criteria**

- [x] Given a logged in user, a functionality to create comments is available on each blog post
- [x] Given that the writer of the comment is the logged in user, the user can read, update, and delete their comments
- [x] Any user can read submitted comments

**Tasks**

- [x] Create a Comment model
- [x] Design and implement a comment function in the front-end
- [x] Wire up the comment function to the back-end
- [x] Test
