### ISSUE TITLE
USER STORY: Add a category to posts

### ISSUE THREAD

**Issue by MariaHochstoeger** [MariaHochstoeger/el-madre#6]
As an **admin** I can **select a category for my posts** so that **posts can be grouped according to topic**.

**Acceptance Criteria**

- [x] When creating a blog post, a dropdown menu displays possible categories
- [x] One category must be chosen, if no category is chosen, a default category is applied (here: Miscellaneous)
- [x] The category of the blog post is displayed with the blog post

**Tasks**

- [x] Create category model
- [x] Create categories
- [x] Test functionality
