### ISSUE TITLE
USER STORY: Choose a category of posts

### ISSUE THREAD

**Issue by MariaHochstoeger** [MariaHochstoeger/el-madre#7]
As a **logged in user** I can **choose a category of blog posts** so that **I see those posts which correspond to the topic I am interested in**.

**Acceptance Criteria**

- [x] A logged in user sees a menu to choose a category from
- [x] Upon choosing a category, only posts belonging to this category are displayed
- [x] A logged in user can switch between categories

**Tasks**

- [x] Design and implement functionality to choose from a category
- [x] Test that only the posts belonging to the category are displayed
