### ISSUE TITLE
USER STORY: Favourite posts

### ISSUE THREAD

**Issue by MariaHochstoeger** [MariaHochstoeger/el-madre#9]
As a **user** I can **favourite individual posts** so that **I can retrieve them with ease**.

**Acceptance Criteria**

- [x] Given a logged in user, they can favourite an individual post by clicking on a button
- [x] Bookmarked posts are displayed in a separate section ("Favourites")
- [x] Users get meaningful feedback via modal messages

**Tasks**

- [x] Create Favourites FK
- [x] Design and implement the functionality on the page
- [x] Create modals
- [x] Test
